# Lab 1 – K-Nearest Neighbours

In this lab session, we will implement the K-Nearest Neighbours (KNN) algorithm.  

Specifically, we will work through a typical machine learning pipeline, which involves:

1. Defining the problem we want to solve
2. Collecting the data
3. Preprocessing the data
4. Define the variables of the problem
5. Implementing a KNN model
6. Use the model to make predictions on unseen data

#### Lab Materials

1. The KNN slides available on ILIAS.
2. For an introduction to Python and useful libraries, we highly recommend reviewing the chapter **“2.3 Lab: Introduction to Python”** from the book *An Introduction to Statistical Learning*.

The book is available [here](https://www.statlearning.com/).

# Step 1&2: Defining the Problem

In this lab, we will use the data collected during the course to create a model that predicts the use of AI based on the available variables.

We begin by loading the data into a Pandas DataFrame.

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("class.csv")

In [3]:
# First, we rename the columns for convenience.
rename_dict = {
               'grade %': 'grade',
               'sport (hours)':'sport',
               'drugs (Alc/Coffee)':'drugs',
               'AI use [0, 1, 2, 3]: 3 means it solves everything, 1 means I use it when stuck, and 2 is: I verify what it does':"AI_ussage"
              }
data.rename(columns= rename_dict,inplace =True)

In [4]:
data

   Name    grade  device  sport        drugs  AI_ussage
0    CD   65.000     8.0    7.0   Alc+Coffee        1.0
1    JU   50.000     5.0    6.0       Coffe         1.0
2    BV   85.000     8.0    7.0   Alc+Coffee        1.0
3    FM   55.000     3.0    3.0            -        2.0
4    EG   68.000     5.0    9.0          Alc        2.0
5    EG   76.000    10.0    2.0       Coffee        1.0
6    AH   85.000     6.0    3.0       Coffee        1.0
7    DC   70.000     8.0    5.0       Coffee        1.0
8    DY   99.500    12.0    0.0      Coffee         2.0
9    FB   77.000     8.0    4.0          NaN        2.0
10   EY   80.000    10.0    2.0   Alc+Coffee        2.0
11   AH  100.000    14.0    0.0   Alc+Coffee        2.0
12   PK  100.000     6.0    1.0      El Tony        NaN
13   AA   80.000    10.0    2.0   Alc+Coffee        2.0
14   ZZ   80.000     8.0    5.0   Alc+Coffee        1.0
15   SN   99.999     9.0    7.0       Coffee        1.0
16   RD   80.000     8.0    2.0            -        1.0
17   EH   75.000     8.0    3.0       Coffee        2.0
18   MM   67.000    10.0    3.0       Coffee        2.0
19   YA      NaN     NaN    NaN          NaN        NaN
20   YC   80.000    12.0    0.0       Coffee        1.0
21   TM   85.000     4.0   12.0       Coffee        1.0
22   LP   80.000     8.0    6.0  Alc + Coffe        1.0
23   NS   72.000     8.0    3.0       Coffee        1.0
24   HE   78.000     5.0    5.0       Coffee        2.0

Because the labels take only two possible values, 1 and 2, we can treat this as a binary classification problem.

For convenience, we relabel the two classes as 0 and 1, where 0 indicates low AI usage and 1 indicates high AI usage.

In [5]:
mapping = {
    1.0: 0,
    2.0: 1
}

data['AI_ussage'] = data['AI_ussage'].map(mapping)

# Step 3: Data Preprocessing

As in many real-world applications, the data contain inconsistencies and require preprocessing. 

There is no single correct way to preprocess a dataset, and the choices made during preprocessing can significantly affect the algorithm’s performance.

For example, we can observe that the `drugs` column contains categorical values, which must be encoded numerically before they can be used by the KNN algorithm.

In [6]:
# Example of label encoding a categorical column
mapping = {
    'Coffee': 1,
    'Alc': 2,
    'Alc+Coffee': 3
}

data['drugs'] = data['drugs'].map(mapping)

In [7]:
data

   Name    grade  device  sport  drugs  AI_ussage
0    CD   65.000     8.0    7.0    3.0        0.0
1    JU   50.000     5.0    6.0    NaN        0.0
2    BV   85.000     8.0    7.0    3.0        0.0
3    FM   55.000     3.0    3.0    NaN        1.0
4    EG   68.000     5.0    9.0    2.0        1.0
5    EG   76.000    10.0    2.0    1.0        0.0
6    AH   85.000     6.0    3.0    1.0        0.0
7    DC   70.000     8.0    5.0    1.0        0.0
8    DY   99.500    12.0    0.0    NaN        1.0
9    FB   77.000     8.0    4.0    NaN        1.0
10   EY   80.000    10.0    2.0    3.0        1.0
11   AH  100.000    14.0    0.0    3.0        1.0
12   PK  100.000     6.0    1.0    NaN        NaN
13   AA   80.000    10.0    2.0    3.0        1.0
14   ZZ   80.000     8.0    5.0    3.0        0.0
15   SN   99.999     9.0    7.0    1.0        0.0
16   RD   80.000     8.0    2.0    NaN        0.0
17   EH   75.000     8.0    3.0    1.0        1.0
18   MM   67.000    10.0    3.0    1.0        1.0
19   YA      NaN     NaN    NaN    NaN        NaN
20   YC   80.000    12.0    0.0    1.0        0.0
21   TM   85.000     4.0   12.0    1.0        0.0
22   LP   80.000     8.0    6.0    NaN        0.0
23   NS   72.000     8.0    3.0    1.0        0.0
24   HE   78.000     5.0    5.0    1.0        1.0

Before implementing KNN, examine the dataset and answer the following questions:

1. What problems or inconsistencies do you observe in the data?
2. What preprocessing steps did you apply?
3. How might these choices affect the performance of the classifier?

# Step 4: Define the Problem Variables

Which variables will you use to predict AI_usage?

In [8]:
# Define variables
label = "AI_ussage"
features = [] # fill this.

# Step 5: Implement the KNN Algorithm

Below, we provide a template for the KNN model that you must complete.

More specifically, you should:

1. Implement the `get_probabilities(self, x)` method, which estimates the probability of each class for a test sample `x`.
2. Implement the `predict` method, which returns the class label with the highest estimated probability.

In [9]:
def euclidean_metric(x, y):
    return np.linalg.norm(x - y)


## Skeleton code to be filled in
class NearestNeighbourClassifier:
    ## Initialise the neighbours with a specific metric function and dataset
    ## Assume labels are in {1, ..., m}
    def __init__(self, data, labels, metric, K):
        self.metric = metric
        self.data = data
        self.labels = labels
        self.n_classes = len(np.unique(labels))  # Counts actual number of labels
        self.K = K
        self.n_points = data.shape[0] # np array dimensions
        self.n_features = data.shape[1]
        print("classes: ", self.n_classes)

    # Gives a utility for every possible choice made by the algorithm
    def decide(self, U, x):
        """
        A method that return the action that maximise the expected utility.
        :param U: is a 2 denominational array that indicated the utility of each action a given y
                    example: U = np.array([ [ 1 , -1000],
                                            [ -1 ,    0]  ])
                            so U[1,0]=-1 is the utility of taking action a=1 when y=0.
        :param x: the test point.
        :return: the action that maximises the expected utility max_a E[U|a,x].
                 where E[U|a,x] = sum_y P(y|x) U(a,y).
        """
        # HINT:
        # Need to use the get_probabilities function to return the action with the highest
        # expected utility
        # i.e. maximising sum_y P(y|x) U(a,y)
        pass
    
    ## predict the most likely label
    def predict(self, x):
        # calculate the probabilities of different clases
        pass
    

    ## return a vector of probabilities, one for each label
    ## Each component of the vector corresponds to the ratio of that same label in the set of neighbours
    def get_probabilities(self, x):
        # 1. calculate distances
        # 2. sort data using argsort
        # 3. get K closest neighbours
        # 4. get the proportion of each label so that proportions[y] is the proportion of label y in the neighbourhood
        # 5. Return proportion
        pass

In [10]:
kNN = NearestNeighbourClassifier(data = , 
                                 labels= ,
                                 K = ,
                                 metric = euclidean_metric)

SyntaxError: invalid syntax (635027256.py, line 1)

##### Question
After implementing your algorithm, evaluate its accuracy on the entire training set using \(k=1\) and \(k=5\).
What do you observe?

# Step 6: Utility-Based Decisions

We will now use a utility function to make predictions. 
More specifically, for each data point, we will select the action that maximizes the expected utility.

The utility matrix \(U\) is a two-dimensional array in which \(U[a,y]\) represents the utility of taking action \(a\) when the true class is \(y\).

For example:

```python
U = np.array([
    [ 1, -1000],
    [-1,     0]
])
```

In this example:

* $U[0,0]=1$: the utility of selecting action $0$ when the true class is \(0\).
* $U[0,1]=-1000$: the utility of selecting action $0$ when the true class is \(1\).
* $U[1,0]=-1$: the utility of selecting action $1$ when the true class is $0.
* $U[1,1]=0$: the utility of selecting action $1$ when the true class is $1$.

#### tasks
1) First, implement the `decide` method.
2) Then, use each of the two utility functions below (U_1 and U_2) to make predictions with KNN for \(k=3\), and calculate the resulting accuracy.

What do you observe? How does the accuracy obtained with each utility function compare with the accuracy of the standard KNN classifier?

In [ ]:
U_1 = np.array([[1, 0],
                [0, 1]])


U_2 = np.array([[1, -1000],
                [-1, 1]])